
import { Game } from './types';

export const GAMES: Game[] = [
  {
    id: '1',
    title: 'Cyber-Neon 2077',
    description: 'Explore a sprawling metropolis where technology and humanity collide in a neon-drenched dystopia.',
    price: 59.99,
    rating: 4.8,
    category: 'RPG',
    platform: 'PC',
    image: 'https://picsum.photos/seed/cyber/800/450',
    tags: ['Open World', 'Sci-Fi', 'Action'],
    isFeatured: true,
    releaseYear: 2023
  },
  {
    id: '2',
    title: 'Ethereal Souls',
    description: 'Face legendary bosses in a beautifully haunting gothic landscape. Every death is a lesson.',
    price: 49.99,
    rating: 4.9,
    category: 'Action',
    platform: 'PS5',
    image: 'https://picsum.photos/seed/souls/800/450',
    tags: ['Hardcore', 'Dark Fantasy', 'Masterpiece'],
    isFeatured: true,
    releaseYear: 2024
  },
  {
    id: '31',
    title: 'Cricket 26',
    description: 'The most realistic cricket simulation ever made. Experience the Ashes, World Cup, and IPL with stunning photorealism.',
    price: 64.99,
    rating: 4.8,
    category: 'Sports',
    platform: 'Multi',
    image: 'https://picsum.photos/seed/cricket26/800/450',
    tags: ['Cricket', 'Realistic', 'Multiplayer'],
    isFeatured: true,
    releaseYear: 2024
  },
  {
    id: '32',
    title: 'WWE 2K26',
    description: 'Step into the squared circle with the largest roster in history. Relive iconic matches in the new Showcase mode.',
    price: 69.99,
    rating: 4.7,
    category: 'Fighting',
    platform: 'Multi',
    image: 'https://picsum.photos/seed/wwe2k26/800/450',
    tags: ['Wrestling', 'Action', 'Fighting'],
    isFeatured: true,
    releaseYear: 2024
  },
  {
    id: '33',
    title: 'Football Elite 2025',
    description: 'Master the pitch with advanced tactical AI and revolutionary ball physics. Lead your club to glory.',
    price: 59.99,
    rating: 4.5,
    category: 'Sports',
    platform: 'Multi',
    image: 'https://picsum.photos/seed/football25/800/450',
    tags: ['Football', 'Soccer', 'Management'],
    releaseYear: 2024
  },
  {
    id: '34',
    title: 'Mortal Kombat: Legacy',
    description: 'The bloodiest entry yet. Use the environment to perform gruesome fatalities in this next-gen fighter.',
    price: 59.99,
    rating: 4.9,
    category: 'Action',
    platform: 'PS5',
    image: 'https://picsum.photos/seed/mklegacy/800/450',
    tags: ['Gory', 'Competitive', 'Martial Arts'],
    releaseYear: 2024
  },
  {
    id: '35',
    title: 'Street Brawler X',
    description: 'A love letter to classic arcade fighters. High-octane combos and vibrant cel-shaded graphics.',
    price: 29.99,
    rating: 4.3,
    category: 'Fighting',
    platform: 'PC',
    image: 'https://picsum.photos/seed/brawlerx/800/450',
    tags: ['Arcade', '2D Fighter', 'Retro'],
    releaseYear: 2023
  },
  {
    id: '36',
    title: 'IPL Fever 2024',
    description: 'Experience the electric atmosphere of the Indian Premier League. Build your dream team in Auction Mode.',
    price: 14.99,
    rating: 4.6,
    category: 'Sports',
    platform: 'Mobile',
    image: 'https://picsum.photos/seed/ipl2024/800/450',
    tags: ['Cricket', 'Mobile Gaming', 'Fast-Paced'],
    releaseYear: 2024
  },
  {
    id: '37',
    title: 'Tekken Frontier',
    description: 'The Iron Fist Tournament goes open-world. Explore, train, and fight legendary masters in 4K.',
    price: 69.99,
    rating: 4.8,
    category: 'Fighting',
    platform: 'PS5',
    image: 'https://picsum.photos/seed/tekkenf/800/450',
    tags: ['3D Fighter', 'Story Mode', 'Technique'],
    releaseYear: 2024
  },
  {
    id: '38',
    title: 'UFC: Apex Warrior',
    description: 'Real-time damage and stamina systems. Feel every strike in the most authentic MMA experience.',
    price: 59.99,
    rating: 4.2,
    category: 'Fighting',
    platform: 'Xbox',
    image: 'https://picsum.photos/seed/ufcapex/800/450',
    tags: ['MMA', 'Simulation', 'Combat'],
    releaseYear: 2023
  },
  {
    id: '39',
    title: 'Big Bash Blitz',
    description: 'Arcade-style cricket with power-ups and explosive boundary hits. Perfect for quick sessions.',
    price: 9.99,
    rating: 4.4,
    category: 'Sports',
    platform: 'Mobile',
    image: 'https://picsum.photos/seed/bigbash/800/450',
    tags: ['Cricket', 'Arcade', 'Family'],
    releaseYear: 2023
  },
  {
    id: '40',
    title: 'Golden Boot 2024',
    description: 'Focus on the striker life. Perfect your shots and climb from the Sunday leagues to the World Cup.',
    price: 0.00,
    rating: 4.1,
    category: 'Sports',
    platform: 'Mobile',
    image: 'https://picsum.photos/seed/goldenboot/800/450',
    tags: ['Soccer', 'Skill-Based', 'Free'],
    releaseYear: 2024
  },
  {
    id: '41',
    title: 'Iron Soul Tournament',
    description: 'A weapon-based fighter set in a mystical feudal Japan. Master the blade to claim the Iron Soul.',
    price: 39.99,
    rating: 4.7,
    category: 'Fighting',
    platform: 'PC',
    image: 'https://picsum.photos/seed/ironsoul/800/450',
    tags: ['Samurai', 'Weapon Fighting', 'Indie'],
    releaseYear: 2023
  },
  {
    id: '42',
    title: 'Ashes: Bound for Glory',
    description: 'The ultimate test of endurance. Play full 5-day tests with dynamic pitch wear and tear.',
    price: 49.99,
    rating: 4.5,
    category: 'Sports',
    platform: 'PC',
    image: 'https://picsum.photos/seed/ashes/800/450',
    tags: ['Cricket', 'Simulation', 'Strategy'],
    releaseYear: 2022
  },
  {
    id: '43',
    title: 'Punch-Out Revolution',
    description: 'The classic returns! Use motion controls to dodge, weave, and hook your way to the championship.',
    price: 19.99,
    rating: 4.6,
    category: 'Fighting',
    platform: 'Multi',
    image: 'https://picsum.photos/seed/punchout/800/450',
    tags: ['Boxing', 'Rhythm', 'Funny'],
    releaseYear: 2023
  },
  {
    id: '44',
    title: 'Quarterback Pro 26',
    description: 'Tactical American football with deep franchise management and incredible tackle physics.',
    price: 64.99,
    rating: 4.3,
    category: 'Sports',
    platform: 'Xbox',
    image: 'https://picsum.photos/seed/qbpro/800/450',
    tags: ['Football', 'Strategy', 'NFL'],
    releaseYear: 2024
  },
  {
    id: '45',
    title: 'Dungeon Brawler',
    description: 'A mix of fighting and RPG elements. Battle through floors of enemies in this side-scrolling mashup.',
    price: 14.99,
    rating: 4.8,
    category: 'Fighting',
    // Fix: Changed 'Indie' to 'PC' to match Game.platform type definition
    platform: 'PC',
    image: 'https://picsum.photos/seed/dbrawler/800/450',
    tags: ['Roguelike', 'Beat-em-up', 'Pixel Art'],
    releaseYear: 2024
  },
  {
    id: '3',
    title: 'Starlight Odyssey',
    description: 'An infinite universe awaits. Pilot your starship through uncharted systems and build your empire.',
    price: 39.99,
    rating: 4.5,
    category: 'Simulation',
    platform: 'PC',
    image: 'https://picsum.photos/seed/space/800/450',
    tags: ['Space', 'Exploration', 'Strategy'],
    releaseYear: 2022
  },
  {
    id: '4',
    title: 'Mythic Conquest',
    description: 'Lead your armies in real-time tactical battles that span eras. History is yours to write.',
    price: 29.99,
    rating: 4.2,
    category: 'Strategy',
    platform: 'PC',
    image: 'https://picsum.photos/seed/strategy/800/450',
    tags: ['RTS', 'Historical', 'Multiplayer'],
    releaseYear: 2021
  },
  {
    id: '5',
    title: 'Verdant Valley',
    description: 'Find peace in this farming sim. Build your homestead, make friends, and discover hidden secrets.',
    price: 19.99,
    rating: 4.9,
    category: 'Indie',
    platform: 'Multi',
    image: 'https://picsum.photos/seed/farm/800/450',
    tags: ['Cozy', 'Relaxing', 'Pixel Art'],
    releaseYear: 2023
  },
  {
    id: '6',
    title: 'Shadow Protocol',
    description: 'Stealth-based tactical shooter. Every move counts when you are behind enemy lines.',
    price: 44.99,
    rating: 4.4,
    category: 'Shooter',
    platform: 'Xbox',
    image: 'https://picsum.photos/seed/stealth/800/450',
    tags: ['Tactical', 'First-Person', 'Stealth'],
    releaseYear: 2024
  },
  {
    id: '7',
    title: 'Pulse Racer Ultra',
    description: 'High-speed gravity-defying racing. Custom ships, lethal weapons, and blistering beats.',
    price: 24.99,
    rating: 4.7,
    category: 'Racing',
    platform: 'Multi',
    image: 'https://picsum.photos/seed/racing/800/450',
    tags: ['Arcade', 'Fast-Paced', 'Electronic'],
    releaseYear: 2022
  },
  {
    id: '8',
    title: 'Arcane Legends',
    description: 'A co-op dungeon crawler where magic is your primary weapon. Combine elements for devastating effects.',
    price: 34.99,
    rating: 4.6,
    category: 'RPG',
    platform: 'Multi',
    image: 'https://picsum.photos/seed/magic/800/450',
    tags: ['Co-op', 'Magic', 'Fantasy'],
    releaseYear: 2023
  },
  {
    id: '9',
    title: 'Genshin Legacy',
    description: 'Embark on a massive open-world adventure with elemental magic and diverse characters.',
    price: 0.00,
    rating: 4.7,
    category: 'RPG',
    platform: 'Mobile',
    image: 'https://picsum.photos/seed/genshin/800/450',
    tags: ['Anime', 'Open World', 'Free to Play'],
    releaseYear: 2024
  },
  {
    id: '10',
    title: 'Halo: Eternal Skies',
    description: 'Step back into the boots of the Master Chief in the most expansive Halo campaign yet.',
    price: 59.99,
    rating: 4.6,
    category: 'Shooter',
    platform: 'Xbox',
    image: 'https://picsum.photos/seed/halo/800/450',
    tags: ['Sci-Fi', 'Arena', 'Multiplayer'],
    releaseYear: 2023
  },
  {
    id: '11',
    title: 'God of War: Dynasty',
    description: 'Kratos and Atreus continue their journey through the frozen wastes of the Norse realms.',
    price: 69.99,
    rating: 5.0,
    category: 'Action',
    platform: 'PS5',
    image: 'https://picsum.photos/seed/gow/800/450',
    tags: ['Cinematic', 'Narrative', 'Combat'],
    releaseYear: 2024
  },
  {
    id: '12',
    title: 'Candy Crush: Ultimate',
    description: 'The world\'s most popular puzzle game returns with thousands of new levels and social features.',
    price: 0.00,
    rating: 4.2,
    category: 'Indie',
    platform: 'Mobile',
    image: 'https://picsum.photos/seed/candy/800/450',
    tags: ['Casual', 'Puzzle', 'Addictive'],
    releaseYear: 2024
  },
  {
    id: '13',
    title: 'Forza Horizon: Japan',
    description: 'Drive across the vibrant landscapes of Japan in the most social and stunning racing sim ever.',
    price: 59.99,
    rating: 4.9,
    category: 'Racing',
    platform: 'Xbox',
    image: 'https://picsum.photos/seed/forza/800/450',
    tags: ['Open World', 'Cars', 'Social'],
    releaseYear: 2024
  },
  {
    id: '14',
    title: 'Raid: Shadow Legends Pro',
    description: 'Collect hundreds of champions and battle in epic fantasy environments.',
    price: 0.00,
    rating: 3.9,
    category: 'RPG',
    platform: 'Mobile',
    image: 'https://picsum.photos/seed/raid/800/450',
    tags: ['Turn-Based', 'Gacha', 'Fantasy'],
    releaseYear: 2023
  },
  {
    id: '15',
    title: 'Flight Sim 2025',
    description: 'Experience true-to-life flight simulation with real-time weather and 1:1 earth mapping.',
    price: 59.99,
    rating: 4.8,
    category: 'Simulation',
    platform: 'PC',
    image: 'https://picsum.photos/seed/plane/800/450',
    tags: ['Realistic', 'Aviation', 'Relaxing'],
    releaseYear: 2024
  },
  {
    id: '16',
    title: 'Ghost of Tsushima 2',
    description: 'The story of the Ghost continues as new threats emerge in feudal Japan.',
    price: 69.99,
    rating: 4.9,
    category: 'Action',
    platform: 'PS5',
    image: 'https://picsum.photos/seed/ghost/800/450',
    tags: ['Ninja', 'Samurai', 'Open World'],
    releaseYear: 2024
  },
  {
    id: '17',
    title: 'Clash of Realms',
    description: 'Build your village, raise a clan, and compete in epic Clan Wars!',
    price: 0.00,
    rating: 4.5,
    category: 'Strategy',
    platform: 'Mobile',
    image: 'https://picsum.photos/seed/clash/800/450',
    tags: ['Competitive', 'Building', 'Social'],
    releaseYear: 2022
  },
  {
    id: '18',
    title: 'Spider-Man: Nexus',
    description: 'Swing through New York as Peter Parker and Miles Morales in their biggest adventure yet.',
    price: 69.99,
    rating: 4.9,
    category: 'Action',
    platform: 'PS5',
    image: 'https://picsum.photos/seed/spiderman/800/450',
    tags: ['Superheroes', 'Action', 'Marvel'],
    releaseYear: 2023
  },
  {
    id: '19',
    title: 'Starfield Prime',
    description: 'From the creators of Skyrim, explore a massive star system with over 1000 planets.',
    price: 69.99,
    rating: 4.1,
    category: 'RPG',
    platform: 'Xbox',
    image: 'https://picsum.photos/seed/starfield/800/450',
    tags: ['Space', 'RPG', 'Bethesda'],
    releaseYear: 2023
  },
  {
    id: '20',
    title: 'Among Us VR',
    description: 'The ultimate party game of betrayal and survival, now in fully immersive virtual reality.',
    price: 19.99,
    rating: 4.6,
    category: 'Indie',
    platform: 'PC',
    image: 'https://picsum.photos/seed/amongus/800/450',
    tags: ['Social Deduction', 'VR', 'Multiplayer'],
    releaseYear: 2022
  },
  {
    id: '21',
    title: 'Civilization VII',
    description: 'Build an empire to stand the test of time in the newest entry of the legendary 4X strategy series.',
    price: 59.99,
    rating: 4.7,
    category: 'Strategy',
    platform: 'PC',
    image: 'https://picsum.photos/seed/civ/800/450',
    tags: ['4X', 'Turn-Based', 'History'],
    releaseYear: 2024
  },
  {
    id: '22',
    title: 'Final Fantasy VII Rebirth',
    description: 'The journey beyond Midgar begins in this stunning reimagining of a gaming classic.',
    price: 69.99,
    rating: 4.9,
    category: 'RPG',
    platform: 'PS5',
    image: 'https://picsum.photos/seed/ff7/800/450',
    tags: ['JRPG', 'Classic', 'Epic'],
    releaseYear: 2024
  },
  {
    id: '23',
    title: 'Gears: Awakening',
    description: 'The battle for survival continues on Sera with brutal combat and deep emotional stakes.',
    price: 59.99,
    rating: 4.4,
    category: 'Shooter',
    platform: 'Xbox',
    image: 'https://picsum.photos/seed/gears/800/450',
    tags: ['Cover Shooter', 'Co-op', 'Action'],
    releaseYear: 2024
  },
  {
    id: '24',
    title: 'Marvel Snap Infinity',
    description: 'Assemble your team of Marvel heroes and villains in this fast-paced card battler.',
    price: 0.00,
    rating: 4.8,
    category: 'Strategy',
    platform: 'Mobile',
    image: 'https://picsum.photos/seed/snap/800/450',
    tags: ['Card Game', 'Competitive', 'Short Sessions'],
    releaseYear: 2023
  },
  {
    id: '25',
    title: 'Gran Turismo 8',
    description: 'The real driving simulator returns with ultra-realistic graphics and hundreds of cars.',
    price: 69.99,
    rating: 4.7,
    category: 'Racing',
    platform: 'PS5',
    image: 'https://picsum.photos/seed/gt/800/450',
    tags: ['Simulation', 'Motorsport', 'Visuals'],
    releaseYear: 2024
  },
  {
    id: '26',
    title: 'Stardew Valley Mobile',
    description: 'Take your farm on the go in this beloved country-life RPG.',
    price: 4.99,
    rating: 4.9,
    category: 'Indie',
    platform: 'Mobile',
    image: 'https://picsum.photos/seed/stardew/800/450',
    tags: ['Relaxing', 'Farming', 'Indie'],
    releaseYear: 2021
  },
  {
    id: '27',
    title: 'Warzone Nexus',
    description: 'Drop in, armor up, and loot your way to the top in this massive free-to-play battle royale.',
    price: 0.00,
    rating: 4.0,
    category: 'Shooter',
    platform: 'Multi',
    image: 'https://picsum.photos/seed/warzone/800/450',
    tags: ['Battle Royale', 'Action', 'Co-op'],
    releaseYear: 2023
  },
  {
    id: '28',
    title: 'Sea of Thieves',
    description: 'Be the pirate you want to be in a shared-world adventure filled with danger and discovery.',
    price: 39.99,
    rating: 4.5,
    category: 'Action',
    platform: 'Xbox',
    image: 'https://picsum.photos/seed/sea/800/450',
    tags: ['Pirates', 'Open World', 'Social'],
    releaseYear: 2022
  },
  {
    id: '29',
    title: 'League of Legends: Wild Rift',
    description: 'Fast-paced MOBA action specifically designed for mobile devices.',
    price: 0.00,
    rating: 4.4,
    category: 'Strategy',
    platform: 'Mobile',
    image: 'https://picsum.photos/seed/lol/800/450',
    tags: ['MOBA', 'Competitive', 'Teamwork'],
    releaseYear: 2023
  },
  {
    id: '30',
    title: 'Ratchet & Clank: Rift Apart',
    description: 'Blast your way through an interdimensional adventure with the galaxy\'s favorite duo.',
    price: 59.99,
    rating: 4.9,
    category: 'Action',
    platform: 'PS5',
    image: 'https://picsum.photos/seed/ratchet/800/450',
    tags: ['Platformer', 'Family Friendly', 'Technical Showcase'],
    releaseYear: 2023
  }
];

export const CATEGORIES = ['All', 'Action', 'RPG', 'Strategy', 'Indie', 'Shooter', 'Racing', 'Simulation', 'Sports', 'Fighting'];
export const PLATFORMS = ['All', 'PC', 'Mobile', 'PS5', 'Xbox', 'Multi'];
